all :
	make -C Lib_ipc
	make -C Lib_flux_exec
	make -C Lib_reseau
	make -C Admin
	make -C Bot
	make -C c_and_c
	make -C serveur_http
	make -C serveur_http/lib_dynamique


clean :
	make -C Admin clean
	make -C Bot clean
	make -C c_and_c clean
	make -C serveur_http clean
	make -C serveur_http/lib_dynamique clean
	make -C Lib_ipc clean
	make -C Lib_flux_exec clean
	make -C Lib_reseau clean

debug :
	make -C Lib_ipc
	make -C Lib_flux_exec
	make -C Lib_reseau
	make -C Admin debug
	make -C Bot debug
	make -C c_and_c debug
	make -C serveur_http debug
	make -C serveur_http/lib_dynamique

passupload :
	make -C Lib_ipc
	make -C Lib_flux_exec
	make -C Lib_reseau
	make -C Admin
	make -C Bot
	make -C c_and_c passupload
	make -C serveur_http
	make -C serveur_http/lib_dynamique
